<a href="https://colab.research.google.com/github/dkaybee2022/Automation-Radiology-Project-/blob/main/Radiology_Automation_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
# 1. Load Excel file
df = pd.read_excel("/content/FINAL radiology_operations_data.xlsx")

In [5]:
from google.colab import files

print("Please upload 'FINAL radiology_operations_data.xlsx' now. Ensure it's in the root /content/ directory.")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'Successfully uploaded "{fn}" with length {len(uploaded[fn])} bytes')

Please upload 'FINAL radiology_operations_data.xlsx' now. Ensure it's in the root /content/ directory.

Saving FINAL radiology_operations_data.xlsx to FINAL radiology_operations_data (1).xlsx
Successfully uploaded "FINAL radiology_operations_data (1).xlsx" with length 12359 bytes

In [6]:
df.info()
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Exam_Date              24 non-null     datetime64[ns]
 1   Location               24 non-null     object
 2   Modality               24 non-null     object
 3   Radiologist            24 non-null     object
 4   Exam_Start_Time        24 non-null     object
 5   Exam_End_Time          24 non-null     object
 6   Report_Signed_Time     24 non-null     object
 7   Revenue_Per_Exam       24 non-null     int64
 8   Cost_Per_Exam          24 non-null     int64
 9   Exam_Duration_Minutes  24 non-null     object
dtypes: datetime64[ns](1), int64(2), object(7)
memory usage: 2.0+ KB

In [7]:
df.head()

,Exam_Date,Location,Modality,Radiologist,Exam_Start_Time,Exam_End_Time,Report_Signed_Time,Revenue_Per_Exam,Cost_Per_Exam,Exam_Duration_Minutes
0,2024-01-03,Raleigh,MRI,Dr. Smith,08:00:00,08:45:00,11:30:00,1200,450,00:45:00
1,2024-01-03,Raleigh,CT,Dr. Smith,09:00:00,09:25:00,10:15:00,650,220,00:25:00
2,2024-01-03,Cary,X-Ray,Dr. Johnson,10:00:00,10:10:00,10:45:00,180,60,00:10:00
3,2024-01-04,Cary,Ultrasound,Dr. Johnson,11:00:00,11:30:00,12:15:00,350,120,00:30:00
4,2024-01-04,Raleigh,MRI,Dr. Lee,12:00:00,12:50:00,16:00:00,1200,450,00:50:00

In [8]:
df['Exam_Date'] = pd.to_datetime(df['Exam_Date'])

df['Month'] = df['Exam_Date'].dt.month
df['Year'] = df['Exam_Date'].dt.year
df['Weekday'] = df['Exam_Date'].dt.day_name()

In [9]:
df.head()

,Exam_Date,Location,Modality,Radiologist,Exam_Start_Time,Exam_End_Time,Report_Signed_Time,Revenue_Per_Exam,Cost_Per_Exam,Exam_Duration_Minutes,Month,Year,Weekday
0,2024-01-03,Raleigh,MRI,Dr. Smith,08:00:00,08:45:00,11:30:00,1200,450,00:45:00,1,2024,Wednesday
1,2024-01-03,Raleigh,CT,Dr. Smith,09:00:00,09:25:00,10:15:00,650,220,00:25:00,1,2024,Wednesday
2,2024-01-03,Cary,X-Ray,Dr. Johnson,10:00:00,10:10:00,10:45:00,180,60,00:10:00,1,2024,Wednesday
3,2024-01-04,Cary,Ultrasound,Dr. Johnson,11:00:00,11:30:00,12:15:00,350,120,00:30:00,1,2024,Thursday
4,2024-01-04,Raleigh,MRI,Dr. Lee,12:00:00,12:50:00,16:00:00,1200,450,00:50:00,1,2024,Thursday

In [10]:
print('Updated DataFrame Info:')
df.info()
print('\nUpdated DataFrame Head:')
display(df.head())

Updated DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Exam_Date              24 non-null     datetime64[ns]
 1   Location               24 non-null     object
 2   Modality               24 non-null     object
 3   Radiologist            24 non-null     object
 4   Exam_Start_Time        24 non-null     object
 5   Exam_End_Time          24 non-null     object
 6   Report_Signed_Time     24 non-null     object
 7   Revenue_Per_Exam       24 non-null     int64
 8   Cost_Per_Exam          24 non-null     int64
 9   Exam_Duration_Minutes  24 non-null     object
 10  Month                  24 non-null     int32
 11  Year                   24 non-null     int32
 12  Weekday                24 non-null     object
dtypes: datetime64[ns](1), int32(2), int64(2), object(8)
memory usage: 2.4+ KB

Updated DataFrame Head:

,Exam_Date,Location,Modality,Radiologist,Exam_Start_Time,Exam_End_Time,Report_Signed_Time,Revenue_Per_Exam,Cost_Per_Exam,Exam_Duration_Minutes,Month,Year,Weekday
0,2024-01-03,Raleigh,MRI,Dr. Smith,08:00:00,08:45:00,11:30:00,1200,450,00:45:00,1,2024,Wednesday
1,2024-01-03,Raleigh,CT,Dr. Smith,09:00:00,09:25:00,10:15:00,650,220,00:25:00,1,2024,Wednesday
2,2024-01-03,Cary,X-Ray,Dr. Johnson,10:00:00,10:10:00,10:45:00,180,60,00:10:00,1,2024,Wednesday
3,2024-01-04,Cary,Ultrasound,Dr. Johnson,11:00:00,11:30:00,12:15:00,350,120,00:30:00,1,2024,Thursday
4,2024-01-04,Raleigh,MRI,Dr. Lee,12:00:00,12:50:00,16:00:00,1200,450,00:50:00,1,2024,Thursday

In [11]:
df['Exam_Duration_Minutes'] = pd.to_timedelta(df['Exam_Duration_Minutes'].astype(str), errors='coerce').dt.total_seconds() / 60
Exam_Min_Per_Radiologist = df.groupby('Radiologist')['Exam_Duration_Minutes'].sum()

In [12]:
df['Exam_Duration_Minutes'].head()

0    45.0
1    25.0
2    10.0
3    30.0
4    50.0
Name: Exam_Duration_Minutes, dtype: float64

In [13]:
df.groupby('Radiologist')['Exam_Duration_Minutes'].sum()

Radiologist
Dr. Johnson    125.0
Dr. Lee        235.0
Dr. Patel      135.0
Dr. Smith      220.0
Name: Exam_Duration_Minutes, dtype: float64

In [14]:
df[df['Radiologist'] == 'Dr. Johnson']

,Exam_Date,Location,Modality,Radiologist,Exam_Start_Time,Exam_End_Time,Report_Signed_Time,Revenue_Per_Exam,Cost_Per_Exam,Exam_Duration_Minutes,Month,Year,Weekday
2,2024-01-03,Cary,X-Ray,Dr. Johnson,10:00:00,10:10:00,10:45:00,180,60,10.0,1,2024,Wednesday
3,2024-01-04,Cary,Ultrasound,Dr. Johnson,11:00:00,11:30:00,12:15:00,350,120,30.0,1,2024,Thursday
10,2024-01-06,Durham,Ultrasound,Dr. Johnson,12:30:00,13:00:00,14:20:00,360,125,30.0,1,2024,Saturday
11,2024-01-06,Cary,X-Ray,Dr. Johnson,13:30:00,13:45:00,14:10:00,170,65,15.0,1,2024,Saturday
18,2024-01-09,Raleigh,X-Ray,Dr. Johnson,08:00:00,08:10:00,08:40:00,175,62,10.0,1,2024,Tuesday
19,2024-01-09,Cary,Ultrasound,Dr. Johnson,09:00:00,09:30:00,10:30:00,365,128,30.0,1,2024,Tuesday

In [15]:
df[df['Location'] == 'Cary']

,Exam_Date,Location,Modality,Radiologist,Exam_Start_Time,Exam_End_Time,Report_Signed_Time,Revenue_Per_Exam,Cost_Per_Exam,Exam_Duration_Minutes,Month,Year,Weekday
2,2024-01-03,Cary,X-Ray,Dr. Johnson,10:00:00,10:10:00,10:45:00,180,60,10.0,1,2024,Wednesday
3,2024-01-04,Cary,Ultrasound,Dr. Johnson,11:00:00,11:30:00,12:15:00,350,120,30.0,1,2024,Thursday
8,2024-01-05,Cary,MRI,Dr. Smith,10:30:00,11:15:00,15:30:00,1250,480,45.0,1,2024,Friday
11,2024-01-06,Cary,X-Ray,Dr. Johnson,13:30:00,13:45:00,14:10:00,170,65,15.0,1,2024,Saturday
13,2024-01-07,Cary,CT,Dr. Lee,09:30:00,10:00:00,11:40:00,690,235,30.0,1,2024,Sunday
16,2024-01-08,Cary,MRI,Dr. Smith,12:30:00,13:15:00,17:00:00,1300,500,45.0,1,2024,Monday
19,2024-01-09,Cary,Ultrasound,Dr. Johnson,09:00:00,09:30:00,10:30:00,365,128,30.0,1,2024,Tuesday
22,2024-01-10,Cary,X-Ray,Dr. Patel,12:30:00,12:45:00,13:15:00,160,55,15.0,1,2024,Wednesday

In [16]:
df.groupby('Radiologist')['Exam_Duration_Minutes'].mean()

Radiologist
Dr. Johnson    20.833333
Dr. Lee        39.166667
Dr. Patel      22.500000
Dr. Smith      36.666667
Name: Exam_Duration_Minutes, dtype: float64

In [17]:
df.groupby('Location')['Exam_Duration_Minutes'].sum()

Location
Cary       220.0
Durham     200.0
Raleigh    295.0
Name: Exam_Duration_Minutes, dtype: float64

In [18]:
summary = df.groupby(['Location', 'Radiologist'])['Exam_Duration_Minutes'].agg(['mean', 'sum', 'count'])

In [19]:
df.rename(columns={
    'mean': 'Avg_Duration',
    'sum': 'Total_Duration',
    'count': 'Exam_Count'
})

,Exam_Date,Location,Modality,Radiologist,Exam_Start_Time,Exam_End_Time,Report_Signed_Time,Revenue_Per_Exam,Cost_Per_Exam,Exam_Duration_Minutes,Month,Year,Weekday
0,2024-01-03,Raleigh,MRI,Dr. Smith,08:00:00,08:45:00,11:30:00,1200,450,45.0,1,2024,Wednesday
1,2024-01-03,Raleigh,CT,Dr. Smith,09:00:00,09:25:00,10:15:00,650,220,25.0,1,2024,Wednesday
2,2024-01-03,Cary,X-Ray,Dr. Johnson,10:00:00,10:10:00,10:45:00,180,60,10.0,1,2024,Wednesday
3,2024-01-04,Cary,Ultrasound,Dr. Johnson,11:00:00,11:30:00,12:15:00,350,120,30.0,1,2024,Thursday
4,2024-01-04,Raleigh,MRI,Dr. Lee,12:00:00,12:50:00,16:00:00,1200,450,50.0,1,2024,Thursday
5,2024-01-04,Durham,CT,Dr. Lee,13:00:00,13:30:00,14:45:00,700,250,30.0,1,2024,Thursday
6,2024-01-05,Durham,X-Ray,Dr. Patel,08:30:00,08:45:00,09:20:00,160,55,15.0,1,2024,Friday
7,2024-01-05,Raleigh,Ultrasound,Dr. Patel,09:30:00,10:00:00,11:00:00,375,130,30.0,1,2024,Friday
8,2024-01-05,Cary,MRI,Dr. Smith,10:30:00,11:15:00,15:30:00,1250,480,45.0,1,2024,Friday
9,2024-01-06,Raleigh,CT,Dr. Smith,11:30:00,12:00:00,13:10:00,680,240,30.0,1,2024,Saturday
10,2024-01-06,Durham,Ultrasound,Dr. Johnson,12:30:00,13:00:00,14:20:00,360,125,30.0,1,2024,Saturday
11,2024-01-06,Cary,X-Ray,Dr. Johnson,13:30:00,13:45:00,14:10:00,170,65,15.0,1,2024,Saturday
12,2024-01-07,Raleigh,MRI,Dr. Lee,08:15:00,09:00:00,13:30:00,1220,460,45.0,1,2024,Sunday
13,2024-01-07,Cary,CT,Dr. Lee,09:30:00,10:00:00,11:40:00,690,235,30.0,1,2024,Sunday
14,2024-01-07,Durham,X-Ray,Dr. Patel,10:30:00,10:45:00,11:15:00,165,58,15.0,1,2024,Sunday
15,2024-01-08,Raleigh,Ultrasound,Dr. Patel,11:30:00,12:00:00,13:00:00,380,135,30.0,1,2024,Monday
16,2024-01-08,Cary,MRI,Dr. Smith,12:30:00,13:15:00,17:00:00,1300,500,45.0,1,2024,Monday
17,2024-01-08,Durham,CT,Dr. Smith,13:30:00,14:00:00,15:10:00,710,260,30.0,1,2024,Monday
18,2024-01-09,Raleigh,X-Ray,Dr. Johnson,08:00:00,08:10:00,08:40:00,175,62,10.0,1,2024,Tuesday
19,2024-01-09,Cary,Ultrasound,Dr. Johnson,09:00:00,09:30:00,10:30:00,365,128,30.0,1,2024,Tuesday
20,2024-01-09,Durham,MRI,Dr. Lee,10:30:00,11:20:00,16:30:00,1240,470,50.0,1,2024,Tuesday
21,2024-01-10,Raleigh,CT,Dr. Lee,11:30:00,12:00:00,13:30:00,675,230,30.0,1,2024,Wednesday
22,2024-01-10,Cary,X-Ray,Dr. Patel,12:30:00,12:45:00,13:15:00,160,55,15.0,1,2024,Wednesday
23,2024-01-10,Durham,Ultrasound,Dr. Patel,13:30:00,14:00:00,15:00:00,355,120,30.0,1,2024,Wednesday

In [20]:
summary = summary.rename(columns={
    'mean': 'Avg_Duration',
    'sum': 'Total_Duration',
    'count': 'Exam_Count'
})

In [21]:
df = df.dropna(subset=['Exam_Duration_Minutes'])

In [22]:
summary = df.groupby(['Location', 'Radiologist'])['Exam_Duration_Minutes'].agg(['mean', 'sum', 'count']).reset_index()

summary = summary.rename(columns={
    'mean': 'Avg_Duration',
    'sum': 'Total_Duration',
    'count': 'Exam_Count'
})

summary.head()

  Location  Radiologist  Avg_Duration  Total_Duration  Exam_Count
0     Cary  Dr. Johnson         21.25            85.0           4
1     Cary      Dr. Lee         30.00            30.0           1
2     Cary    Dr. Patel         15.00            15.0           1
3     Cary    Dr. Smith         45.00            90.0           2
4   Durham  Dr. Johnson         30.00            30.0           1

In [23]:
df = df.dropna(subset=['Exam_Duration_Minutes'])

In [24]:
summary = df.groupby(['Location', 'Radiologist'])['Exam_Duration_Minutes'].agg(['mean', 'sum', 'count']).reset_index()

summary = summary.rename(columns={
    'mean': 'Avg_Duration',
    'sum': 'Total_Duration',
    'count': 'Exam_Count'
})

summary.head()

  Location  Radiologist  Avg_Duration  Total_Duration  Exam_Count
0     Cary  Dr. Johnson         21.25            85.0           4
1     Cary      Dr. Lee         30.00            30.0           1
2     Cary    Dr. Patel         15.00            15.0           1
3     Cary    Dr. Smith         45.00            90.0           2
4   Durham  Dr. Johnson         30.00            30.0           1

In [25]:
summary.isna().sum()
summary.head()

  Location  Radiologist  Avg_Duration  Total_Duration  Exam_Count
0     Cary  Dr. Johnson         21.25            85.0           4
1     Cary      Dr. Lee         30.00            30.0           1
2     Cary    Dr. Patel         15.00            15.0           1
3     Cary    Dr. Smith         45.00            90.0           2
4   Durham  Dr. Johnson         30.00            30.0           1

In [26]:
df = pd.read_excel("/content/FINAL radiology_operations_data.xlsx")

In [27]:
df = df.dropna(subset=['Exam_Duration_Minutes'])

In [28]:
df.shape

(24, 10)

In [29]:
df['Exam_Duration_Minutes'] = pd.to_timedelta(df['Exam_Duration_Minutes'].astype(str), errors='coerce').dt.total_seconds() / 60
summary = df.groupby(['Location', 'Radiologist'])['Exam_Duration_Minutes'].agg(['mean', 'sum', 'count']).reset_index()

In [30]:
summary = df.groupby(['Location', 'Radiologist'])['Exam_Duration_Minutes'].agg(['mean', 'sum', 'count']).reset_index()

In [31]:
summary = df.groupby('Radiologist').agg(
    Avg_Duration=('Exam_Duration_Minutes', 'mean'),
    Total_Duration=('Exam_Duration_Minutes', 'sum'),
    Exam_Count=('Exam_Duration_Minutes', 'count')
).reset_index()

# Check it in Colab first
summary.head()

   Radiologist  Avg_Duration  Total_Duration  Exam_Count
0  Dr. Johnson     20.833333           125.0           6
1      Dr. Lee     39.166667           235.0           6
2    Dr. Patel     22.500000           135.0           6
3    Dr. Smith     36.666667           220.0           6

In [32]:
df[df['Radiologist'] == 'Dr. Lee'][['Location', 'Radiologist']].drop_duplicates()

   Location Radiologist
4   Raleigh     Dr. Lee
5    Durham     Dr. Lee
13     Cary     Dr. Lee

In [33]:
with pd.ExcelWriter("radiology_automation_report.xlsx") as writer:
    df.to_excel(writer, sheet_name="Cleaned_Data", index=False)
    summary.to_excel(writer, sheet_name="Summary_By_Radiologist", index=False)

In [34]:
from google.colab import files
files.download("radiology_automation_report.xlsx")